apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "zara-fetcher.fullname" . }}
  labels:
    {{- include "zara-fetcher.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            {{- if .Values.postgresql.enabled }}
            - name: APP_DB_HOST
              value: "{{ .Release.Name}}-postgresql"
            - name: APP_DB_PORT
              value: {{ .Values.postgresql.primary.service.ports.postgresql | quote }}
            - name: APP_DB_NAME
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: APP_DB_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: APP_DB_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            {{- end }}
            command:
            - python
            - cli.py
            - fetch-data
          restartPolicy: OnFailure