"""empty message

Revision ID: 033142dc1cfd
Revises: d4ff26dd5a1b
Create Date: 2023-07-27 15:10:09.392299

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '033142dc1cfd'
down_revision = 'd4ff26dd5a1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'product_colors_sizes',
        sa.Column('sku', sa.Text(), autoincrement=False, nullable=False),
        sa.Column('product_color_id', sa.Integer(), nullable=False),
        sa.Column('size_id', sa.Integer(), nullable=False),
        sa.Column('availability', sa.Text(), nullable=True),
        sa.Column('price', sa.Integer(), nullable=True),
        sa.Column('demand', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['product_color_id'],
            ['product_colors.id'],
            name='product_colors_sizes_product_id_fkey',
            onupdate='CASCADE',
            ondelete='RESTRICT',
        ),
        sa.ForeignKeyConstraint(
            ['size_id'],
            ['sizes.id'],
            name='product_colors_sizes_size_id_fkey',
            onupdate='CASCADE',
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('sku'),
    )
    op.create_index(
        op.f('ix_product_colors_sizes_product_color_id'),
        'product_colors_sizes',
        ['product_color_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_product_colors_sizes_size_id'),
        'product_colors_sizes',
        ['size_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_product_colors_sizes_size_id'), table_name='product_colors_sizes'
    )
    op.drop_index(
        op.f('ix_product_colors_sizes_product_color_id'),
        table_name='product_colors_sizes',
    )
    op.drop_table('product_colors_sizes')
    # ### end Alembic commands ###
