"""empty message

Revision ID: 3b8381489ae9
Revises: e642ea468b34
Create Date: 2023-07-27 17:28:52.848609

"""


# revision identifiers, used by Alembic.
revision = '3b8381489ae9'
down_revision = 'e642ea468b34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
