"""empty message

Revision ID: e642ea468b34
Revises: 033142dc1cfd
Create Date: 2023-07-27 15:15:29.096590

"""

# revision identifiers, used by Alembic.
revision = 'e642ea468b34'
down_revision = '033142dc1cfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
